version: "3"
services:
  app:
    build:
      context: app
      dockerfile: ../Dockerfile.dev
    command: bash -c 'npm run start'
    expose:
      - 3000
    ports:
      - "3000:3000"
    volumes:
      - "./app:/app"
